### ISSUE TITLE
Non-terminal tasks being tracked

### ISSUE THREAD

**Issue by paulcanning** [wbingli/zsh-wakatime#17]
I have installed the plugins for PHPStorm, Chrome and iTerm2 (ZSH).

In my dashboard, I am seeing a 'Terminal' project, which shows work done inside the terminal but also shows stuff done in Chrome, which is odd.

I use both PHPStorm and iTerm together, but I cannot seem to collate the data in the dashboard.

PHPStorm plugin seems ot understand when I'm in a project folder and that appears in the dashboard.

How can I make sure that the ZSH plugin is tracking tasks done in iTerm when im inside a folder, and NOT track the Chrome tasks?

**Comment by alanhamlett** [comment]
That activity is coming from the Chrome extension, and can be turned off by clicking the WakaTime icon in Chrome and then choosing "Disable Tracking".

**Comment by wbingli** [comment]
Please track the project detection in #19
