### ISSUE TITLE
Does not seem to log

### ISSUE THREAD

**Issue by BrianKnoblauch** [wbingli/zsh-wakatime#20]
I did the setup and added my API key, however, no logging data is showing up in my dashboard.  I'm on Mac OS 10.5.6.

**Comment by wbingli** [comment]
Thanks for your reporting. The issue has been fixed.  Could you please pull the latest github change and try again? You should see from  https://wakatime.com/projects/Terminal

Other way to trouble shoot it is try `ps | grep wakatime` repeatedly as faster as you as can. You should notice command such as `wakatime --write --plugin zsh-wakatime/0.0.1 --entity-type app --project Terminal --entity...`. You can run that command and make sure it success without problem.

**Comment by wbingli** [comment]
Added troubleshooting section, hope that can help you as well:  https://github.com/wbingli/zsh-wakatime#troubleshooting
