### ISSUE TITLE
How do I undo this command?

### ISSUE THREAD

**Issue by niyonx** [wbingli/zsh-wakatime#21]
wakatime --write --plugin zsh-wakatime/0.0.1 --entity-type app --project Terminal --entity ...

**Comment by wbingli** [comment]
Could you give more details? what you mean of "undo this command"?

**Comment by niyonx** [comment]
I do not use zsh, I use bash so I did this command and now wakatime tracking my terminal as a zsh. I want to make as if I didn't do this command in the first place. Is it possible? Thanks for responding @wbingli !

**Comment by wbingli** [comment]
I don't think so you can undo it. It just sent out a tracking data point to the wakatime.com.  If you are concerning about the data you sending to wakatime.com, you may reach their support to see if they can remove it.

**Comment by niyonx** [comment]
I see, thanks.
