### ISSUE TITLE
By default, $PATH is not set and an alias is not set either

### ISSUE THREAD

**Issue by simonSlamka** [wbingli/zsh-wakatime#22]
Hey!

Just a quick note. I was just setting up this plugin to my macOS installation (using oh-my-zsh) and noticed that some people might get confused since nothing seems to set the `$PATH` variable for the `wakatime-cli`. I would implement a check to verify that it indeed is set and `wakatime` command exists. Also, by default, the wakatime CLI is `wakatime-cli` and not just `wakatime`, so an alias is required also. Maybe it's an isolated issue in macOS, but that's what happened to me just now, so I thought I'd let you know.

Cheers

**Comment by Freed-Wu** [comment]
Fixed by #23
