### ISSUE TITLE
[feature] ignore variable assignment

### ISSUE THREAD

**Issue by Freed-Wu** [wbingli/zsh-wakatime#24]
![screen-2023-01-13-21-59-18](https://user-images.githubusercontent.com/32936898/212337145-5c70b2bd-67c3-4150-827a-1b049166ce5d.jpg)

`SKIP=make` should be ignored, because full command is `SKIP=make git commit`, so the file name should be `git`.

**Comment by Freed-Wu** [comment]
It can fix the problem:

```diff
diff --git a/zsh-wakatime.plugin.zsh b/zsh-wakatime.plugin.zsh
index 4d09d41..694c435 100644
--- a/zsh-wakatime.plugin.zsh
+++ b/zsh-wakatime.plugin.zsh
@@ -28,7 +28,12 @@ waka_filename() {
         echo "$PWD"
     else
 	    # only command without arguments to avoid senstive information
-        echo "$history[$((HISTCMD-1))]" | cut -d ' ' -f1
+        for token in ${(s. .)history[$((HISTCMD-1))]} ; do
+            if ! ((token[(I)=])); then
+                echo $token
+                break
+            fi
+        done
     fi
 }
```

**Comment by wbingli** [comment]
Good one. Will take a look

**Comment by wbingli** [comment]
Thanks @Freed-Wu 

I added you as collaborator for this repo.  Feel free to update or merge PR.

> And transfer this repo to https://github.com/wakatime/ to let the wakatime organization to manage it.

I would still want to have this repo in my account. Thanks

**Comment by Freed-Wu** [comment]
Perhaps you can add @alanhamlett to collabrators. :smile:

**Comment by wbingli** [comment]
haha, absolutely, done!
